-- Generated by ./collectassets.sh
-- Don't edit by hand!
return {
	bonuses = {
		Bombs = require('assets.bonuses.Bombs'),
		Range = require('assets.bonuses.Range'),
	},
	enemies = {
		Balloon = require('assets.enemies.Balloon'),
		Onion = require('assets.enemies.Onion'),
	},
	levels = {
		level1 = require('assets.levels.level1'),
		level2 = require('assets.levels.level2'),
	},
}
