#!/bin/bash

OUTPUT=assets.lua

echo "-- Generated by $0
-- Don't edit by hand!
return {" > $OUTPUT

for GROUP in $(ls assets); do
	echo -e "\t$GROUP = {" >> $OUTPUT
	for ITEM in $(ls assets/$GROUP); do
		NAME=$(basename ${ITEM%.*})
		echo -e "\t\t$NAME = require('assets.$GROUP.$NAME')," >> $OUTPUT
	done
	echo -e "\t}," >> $OUTPUT
done

echo "}" >> $OUTPUT
echo "$OUTPUT updated"
